java -jar /home/jee/Downloads/cfr-0.137.jar ./java/test/com/jeec/game/TestGame.class > ./java/test/com/jeec/game/TestGame.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/Device.class > ./java/main/com/jeec/game/Device.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/forms/BaseGameForm.class > ./java/main/com/jeec/game/forms/BaseGameForm.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/forms/ColorsForm.class > ./java/main/com/jeec/game/forms/ColorsForm.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/forms/SetCardForm.class > ./java/main/com/jeec/game/forms/SetCardForm.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/forms/AddPlayerForm.class > ./java/main/com/jeec/game/forms/AddPlayerForm.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/ColorCode.class > ./java/main/com/jeec/game/ColorCode.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/Application.class > ./java/main/com/jeec/game/Application.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/Game.class > ./java/main/com/jeec/game/Game.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/PlayerState.class > ./java/main/com/jeec/game/PlayerState.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/Round.class > ./java/main/com/jeec/game/Round.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/GameConst.class > ./java/main/com/jeec/game/GameConst.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/GameState.class > ./java/main/com/jeec/game/GameState.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/Player.class > ./java/main/com/jeec/game/Player.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/com/jeec/game/GameController.class > ./java/main/com/jeec/game/GameController.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrCodeGeneratorDemo.class > ./java/main/io/nayuki/qrcodegen/QrCodeGeneratorDemo.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrCode$ReedSolomonGenerator.class > ./java/main/io/nayuki/qrcodegen/QrCode$ReedSolomonGenerator.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrSegmentAdvanced.class > ./java/main/io/nayuki/qrcodegen/QrSegmentAdvanced.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrCodeGeneratorWorker.class > ./java/main/io/nayuki/qrcodegen/QrCodeGeneratorWorker.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrCode.class > ./java/main/io/nayuki/qrcodegen/QrCode.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrSegment.class > ./java/main/io/nayuki/qrcodegen/QrSegment.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrSegment$Mode.class > ./java/main/io/nayuki/qrcodegen/QrSegment$Mode.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/QrCode$Ecc.class > ./java/main/io/nayuki/qrcodegen/QrCode$Ecc.java
java -jar /home/jee/Downloads/cfr-0.137.jar ./java/main/io/nayuki/qrcodegen/BitBuffer.class > ./java/main/io/nayuki/qrcodegen/BitBuffer.java

